# Generated by Django 5.1.7 on 2025-03-17 13:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=255, verbose_name='Ключевое слово')),
                ('location', models.CharField(max_length=100, verbose_name='Геолокация')),
                ('device', models.CharField(max_length=50, verbose_name='Устройство')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Поисковый запрос',
                'verbose_name_plural': 'Поисковые запросы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SearchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Заголовок')),
                ('url', models.URLField(max_length=1000, verbose_name='URL')),
                ('result_type', models.CharField(choices=[('organic', 'Органическая выдача'), ('ad', 'Реклама')], max_length=20, verbose_name='Тип результата')),
                ('position', models.PositiveIntegerField(verbose_name='Позиция в выдаче')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('search_query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='yandex_search_parser.searchquery', verbose_name='Поисковый запрос')),
            ],
            options={
                'verbose_name': 'Результат поиска',
                'verbose_name_plural': 'Результаты поиска',
                'ordering': ['position'],
            },
        ),
    ]
