# Generated by Django 5.1.7 on 2025-03-17 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yandex_search_parser', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='searchresult',
            options={'verbose_name': 'Результат поиска', 'verbose_name_plural': 'Результаты поиска'},
        ),
        migrations.RemoveField(
            model_name='searchresult',
            name='position',
        ),
    ]
